"""Regression: never delete a meeting directory that has real audio.

2026-04-14 data-loss incident: a journal wipe followed by a server
restart triggered ``MeetingStorage._list_meetings_internal`` auto-
cleanup, which deleted the entire f38d5807 meeting directory —
including the 88-minute ``recording.pcm``. Audio is unrecoverable;
everything else (journal, timeline, speaker files, summary) can be
regenerated by reprocess.

The fix: before auto-deleting an "empty" completed/interrupted meeting,
check whether ``audio/recording.pcm`` exists and is non-empty. If so,
PRESERVE the directory and let the user re-reprocess later.

These tests exercise both auto-delete call sites (storage.py and
server.py) to make sure the safety guard stays in place forever.
"""
from __future__ import annotations

import json
from pathlib import Path


def _make_empty_meeting(tmp_path: Path, *, mid: str, state: str,
                       audio_bytes: bytes | None) -> Path:
    meetings = tmp_path / "meetings"
    md = meetings / mid
    md.mkdir(parents=True)
    meta = {
        "meeting_id": mid,
        "state": state,
        "created_at": "2026-04-07T00:00:00+00:00",
        "language_pair": ["ja", "en"],
        "max_attendees": 10,
        "audio_sample_rate": 16000,
        "enrolled_speakers": {},
    }
    (md / "meta.json").write_text(json.dumps(meta))
    # No journal.jsonl → empty meeting as far as the scanner is concerned
    if audio_bytes is not None:
        (md / "audio").mkdir()
        (md / "audio" / "recording.pcm").write_bytes(audio_bytes)
    return md


class TestStorageStartupCleanup:
    """``MeetingStorage._list_meetings_internal`` scans + cleans on every
    startup. The user's session showed that calling it on an empty
    completed meeting with intact audio wiped the audio. Don't."""

    def test_empty_complete_with_audio_is_preserved(self, tmp_path):
        from meeting_scribe.config import ServerConfig
        from meeting_scribe.storage import MeetingStorage

        audio = b"\x00\x01" * 16000  # 1 s of PCM — non-empty
        md = _make_empty_meeting(tmp_path, mid="keep-me", state="complete", audio_bytes=audio)

        cfg = ServerConfig(meetings_dir=tmp_path / "meetings")
        store = MeetingStorage(cfg)

        # Trigger the scan. _list_meetings_internal runs the cleanup
        # inline — any side effects (directory deletion) happen here.
        store.recover_interrupted()

        assert md.exists(), (
            "Empty completed meeting with real audio must be preserved — "
            "audio is unrecoverable, journal can be regenerated via reprocess"
        )
        assert (md / "audio" / "recording.pcm").exists()

    def test_empty_interrupted_with_audio_is_preserved(self, tmp_path):
        from meeting_scribe.config import ServerConfig
        from meeting_scribe.storage import MeetingStorage

        audio = b"\x00\x01" * 16000
        md = _make_empty_meeting(tmp_path, mid="keep-int", state="interrupted", audio_bytes=audio)

        cfg = ServerConfig(meetings_dir=tmp_path / "meetings")
        store = MeetingStorage(cfg)
        store.recover_interrupted()

        assert md.exists()
        assert (md / "audio" / "recording.pcm").exists()

    def test_empty_complete_without_audio_is_deleted(self, tmp_path):
        """If there's NO audio, the old cleanup behaviour is fine —
        a totally-empty meeting carcass (test scaffolding, failed
        start-stop) should still be cleaned up."""
        from meeting_scribe.config import ServerConfig
        from meeting_scribe.storage import MeetingStorage

        md = _make_empty_meeting(tmp_path, mid="drop-me", state="complete", audio_bytes=None)

        cfg = ServerConfig(meetings_dir=tmp_path / "meetings")
        store = MeetingStorage(cfg)
        store.recover_interrupted()

        assert not md.exists(), (
            "Empty meeting with no audio should still be cleaned up"
        )

    def test_empty_complete_with_zero_byte_pcm_is_deleted(self, tmp_path):
        """Edge case: empty file is not real audio. Treat it as no
        audio so we still clean up aborted recordings."""
        from meeting_scribe.config import ServerConfig
        from meeting_scribe.storage import MeetingStorage

        md = _make_empty_meeting(tmp_path, mid="zero-pcm", state="complete", audio_bytes=b"")

        cfg = ServerConfig(meetings_dir=tmp_path / "meetings")
        store = MeetingStorage(cfg)
        store.recover_interrupted()

        assert not md.exists(), (
            "Zero-byte PCM is not real audio; clean up is fine"
        )


class TestServerStopPathCleanup:
    """The /api/meeting/stop handler has its own 'delete empty meeting'
    branch. The static check in the source is cheaper than running a
    FastAPI fixture here."""

    def test_stop_handler_checks_audio_before_delete(self):
        src = (
            Path(__file__).parent.parent
            / "src" / "meeting_scribe" / "server.py"
        ).read_text()
        # The fix adds a `_has_audio` check before `_empty_shutil.rmtree`.
        assert "_has_audio" in src
        # And it logs a "preserving" message when audio is present.
        assert "preserving for reprocess" in src.lower() or "preserve" in src.lower()
