"""``meeting-scribe kiosk`` - HDMI kiosk lifecycle commands.

Sub-commands:
  * ``meeting-scribe kiosk install``   - drop systemd units + udev rule
                                         + symlink the runtime entry,
                                         then daemon-reload + reload
                                         udev rules. Idempotent.
  * ``meeting-scribe kiosk uninstall`` - reverse of install.
  * ``meeting-scribe kiosk up``        - systemctl start kiosk.service.
  * ``meeting-scribe kiosk down``      - systemctl stop kiosk.service.
  * ``meeting-scribe kiosk status``    - systemctl status JSON.
  * ``meeting-scribe kiosk run-runtime`` - cage's ExecStart payload;
       owns the runtime loop (mode enumeration, chromium launch, DPMS).

Privileged file system writes (under ``/etc/systemd/system`` and
``/etc/udev/rules.d``) require sudo; the install / uninstall commands
shell out to ``sudo`` directly. The other lifecycle verbs run as the
operator's user with no extra privileges.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import click

from meeting_scribe.cli import cli

# Source files in the repo (shipped under provisioning/).
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_PROVISIONING_DIR = _REPO_ROOT / "provisioning"
_SOURCE_UNIT_KIOSK = _PROVISIONING_DIR / "systemd" / "meeting-scribe-kiosk.service"
_SOURCE_UNIT_HOTPLUG = _PROVISIONING_DIR / "systemd" / "meeting-scribe-kiosk-hotplug.service"
_SOURCE_UDEV_RULE = _PROVISIONING_DIR / "udev" / "85-meeting-scribe-hdmi-hotplug.rules"

# Installed paths.
_DEST_UNIT_DIR = Path("/etc/systemd/system")
_DEST_UDEV_DIR = Path("/etc/udev/rules.d")
_DEST_BIN = Path("/usr/local/bin/meeting-scribe-kiosk-runtime")

# Kiosk-runtime status snapshot path (the runtime writes this).
_HDMI_STATUS_PATH = Path("/run/meeting-scribe/hdmi-status.json")


@cli.group("kiosk")
def kiosk_group():
    """HDMI kiosk (cage + chromium) lifecycle commands."""


def _sudo_install(src: Path, dest_dir: Path, mode: str = "0644") -> None:
    """Copy ``src`` into ``dest_dir`` as root, preserving permissions."""
    if not src.exists():
        raise click.ClickException(f"source file missing: {src}")
    dest = dest_dir / src.name
    subprocess.run(["sudo", "install", "-m", mode, str(src), str(dest)], check=True)


def _sudo_symlink(target: Path, link: Path) -> None:
    """Create / replace ``link`` -> ``target`` (root-owned)."""
    subprocess.run(["sudo", "ln", "-sfn", str(target), str(link)], check=True)


def _sudo_remove(path: Path) -> None:
    """Remove ``path`` if present (silently)."""
    subprocess.run(["sudo", "rm", "-f", str(path)], check=False)


@kiosk_group.command("install")
@click.option("--no-start", is_flag=True, help="Install units but do not start the kiosk service.")
def kiosk_install(no_start: bool) -> None:
    """Install systemd units + udev rule for the HDMI kiosk."""
    # Locate the kiosk-runtime entry point. The Python script lives in
    # the package as ``meeting_scribe.kiosk.runtime``; we exec it via
    # the meeting-scribe venv's python.
    venv_python = (
        _REPO_ROOT / ".venv" / "bin" / "python3"
        if (_REPO_ROOT / ".venv" / "bin" / "python3").exists()
        else Path(sys.executable)
    )

    # Drop a tiny launcher script at the canonical /usr/local/bin path
    # that the systemd unit's ExecStart references. Using a script
    # wrapper (rather than symlinking python directly) means the unit
    # can stay stable even if the venv path moves.
    launcher_body = (
        "#!/bin/sh\n"
        "# Auto-generated by `meeting-scribe kiosk install`.\n"
        "# Hands off into the kiosk runtime owned by the meeting-scribe venv.\n"
        f'exec {venv_python} -m meeting_scribe.kiosk.runtime "$@"\n'
    )
    tmp_launcher = Path("/tmp/meeting-scribe-kiosk-runtime")
    tmp_launcher.write_text(launcher_body)
    subprocess.run(["sudo", "install", "-m", "0755", str(tmp_launcher), str(_DEST_BIN)], check=True)
    tmp_launcher.unlink(missing_ok=True)

    _sudo_install(_SOURCE_UNIT_KIOSK, _DEST_UNIT_DIR)
    _sudo_install(_SOURCE_UNIT_HOTPLUG, _DEST_UNIT_DIR)
    _sudo_install(_SOURCE_UDEV_RULE, _DEST_UDEV_DIR)

    # Reload systemd + udev so the new units / rules take effect now.
    subprocess.run(["sudo", "systemctl", "daemon-reload"], check=True)
    subprocess.run(["sudo", "udevadm", "control", "--reload-rules"], check=True)
    subprocess.run(["sudo", "udevadm", "trigger", "--subsystem-match=drm"], check=False)

    # Enable the hotplug oneshot so it fires on subsequent DRM events.
    subprocess.run(
        ["sudo", "systemctl", "enable", "meeting-scribe-kiosk-hotplug.service"],
        check=False,
    )

    # Mask gdm.service so a graphical login manager never races us for
    # the DRM seat on tty1. Without this, GDM's Xorg (started with
    # ``-novtswitch -keeptty``) holds DRM master and cage on tty7
    # times out trying to grab the wlroots backend (observed 2026-05-14
    # on the GB10 - "Timeout waiting session to become active"). The
    # kiosk.service has ``Conflicts=gdm.service`` so live transitions
    # are also safe; mask is the boot-time guarantee.
    rc = subprocess.run(
        ["systemctl", "list-unit-files", "gdm.service"],
        capture_output=True,
        text=True,
        check=False,
    )
    if "gdm.service" in rc.stdout:
        subprocess.run(["sudo", "systemctl", "mask", "gdm.service"], check=False)
        subprocess.run(["sudo", "systemctl", "stop", "gdm.service"], check=False)
        click.echo(click.style("    gdm.service masked + stopped", fg="cyan"))

    click.echo(click.style("HDMI kiosk units installed.", fg="green"))

    if not no_start:
        # Best-effort start: if the cable is already connected the
        # hotplug oneshot may already have brought the kiosk up.
        subprocess.run(
            ["sudo", "systemctl", "start", "meeting-scribe-kiosk-hotplug.service"],
            check=False,
        )


@kiosk_group.command("uninstall")
def kiosk_uninstall() -> None:
    """Remove systemd units + udev rule + launcher script."""
    subprocess.run(["sudo", "systemctl", "stop", "meeting-scribe-kiosk.service"], check=False)
    subprocess.run(
        ["sudo", "systemctl", "disable", "meeting-scribe-kiosk-hotplug.service"],
        check=False,
    )
    _sudo_remove(_DEST_UNIT_DIR / "meeting-scribe-kiosk.service")
    _sudo_remove(_DEST_UNIT_DIR / "meeting-scribe-kiosk-hotplug.service")
    _sudo_remove(_DEST_UDEV_DIR / "85-meeting-scribe-hdmi-hotplug.rules")
    _sudo_remove(_DEST_BIN)
    # Reverse the mask gdm.service did during install; harmless when
    # gdm wasn't masked (systemctl unmask exits 0 on already-unmasked).
    rc = subprocess.run(
        ["systemctl", "list-unit-files", "gdm.service"],
        capture_output=True,
        text=True,
        check=False,
    )
    if "gdm.service" in rc.stdout:
        subprocess.run(["sudo", "systemctl", "unmask", "gdm.service"], check=False)
    subprocess.run(["sudo", "systemctl", "daemon-reload"], check=False)
    subprocess.run(["sudo", "udevadm", "control", "--reload-rules"], check=False)
    click.echo(click.style("HDMI kiosk units removed.", fg="green"))


@kiosk_group.command("up")
def kiosk_up() -> None:
    """Start the kiosk service (cage + chromium) on tty7."""
    subprocess.run(["sudo", "systemctl", "start", "meeting-scribe-kiosk.service"], check=True)
    click.echo(click.style("HDMI kiosk started.", fg="green"))


@kiosk_group.command("down")
def kiosk_down() -> None:
    """Stop the kiosk service."""
    subprocess.run(["sudo", "systemctl", "stop", "meeting-scribe-kiosk.service"], check=True)
    click.echo(click.style("HDMI kiosk stopped.", fg="green"))


@kiosk_group.command("status")
@click.option("--json", "as_json", is_flag=True, help="JSON output.")
def kiosk_status(as_json: bool) -> None:
    """Print systemd + HDMI status snapshot."""
    rc = subprocess.run(
        ["systemctl", "is-active", "meeting-scribe-kiosk.service"],
        capture_output=True,
        text=True,
        check=False,
    )
    is_active = rc.stdout.strip() == "active"

    hdmi_status: dict | None = None
    try:
        if _HDMI_STATUS_PATH.exists():
            hdmi_status = json.loads(_HDMI_STATUS_PATH.read_text())
    except Exception as exc:
        hdmi_status = {"error": str(exc)}

    if as_json:
        click.echo(json.dumps({"active": is_active, "hdmi_status": hdmi_status}, indent=2))
        return

    click.echo(f"service:   {'active' if is_active else 'inactive'}")
    if hdmi_status is None:
        click.echo("hdmi:      (no /run/meeting-scribe/hdmi-status.json - kiosk not started yet)")
    else:
        click.echo(
            f"hdmi:      connected={hdmi_status.get('connected')} "
            f"mode={hdmi_status.get('current_mode')} "
            f"rotation={hdmi_status.get('rotation')}"
        )


@kiosk_group.command("mint-nonce")
def kiosk_mint_nonce() -> None:
    """Mint a single-use bootstrap nonce (admin-authenticated).

    Hits ``POST /api/admin/kiosk/mint-nonce`` via the CLI's standard
    admin auth helper so the kiosk-runtime can exchange the result for
    a ``scribe_kiosk`` cookie at ``/kiosk-bootstrap``.
    """
    from meeting_scribe.cli._common import UnauthenticatedRedirect, _api_request

    try:
        parsed = _api_request("/api/admin/kiosk/mint-nonce", method="POST")
    except UnauthenticatedRedirect as exc:
        raise click.ClickException(
            f"mint-nonce failed: server redirected to {exc.suffix} (admin auth required)"
        ) from None
    if not isinstance(parsed, dict):
        raise click.ClickException("mint-nonce failed: no JSON response (admin auth?)")
    click.echo(parsed.get("nonce", ""))


@kiosk_group.command("run-runtime", hidden=True)
def kiosk_run_runtime() -> None:
    """Hidden entry point invoked by the systemd unit inside the cage
    session. Not for interactive use; users want ``kiosk up`` instead.
    """
    # Quiet import-time check that cage / wlr-randr / chromium snap
    # are actually present. Surfaces a clean message instead of a
    # cryptic ENOENT from inside cage.
    for tool in ("wlr-randr", "chromium"):
        if shutil.which(tool) is None:
            click.echo(
                f"meeting-scribe kiosk: missing tool {tool!r} on PATH",
                err=True,
            )
    from meeting_scribe.kiosk.runtime import main as _runtime_main

    _runtime_main()
